# Generated by Django 3.1.7 on 2022-03-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0008_auto_20210316_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('back-end', 'Back-end'), ('front-end', 'Front-end'), ('applications Android ', 'Applications Android '), ('application iOS', 'Application iOS')], max_length=128),
        ),
    ]
